version: "3.9"

volumes:
  shared:

networks:
  default:

services:
  validator:
    image: terraformlabs/${APP_NAME}:${VERSION}
    user: root
    working_dir: /home/${APP_NAME}
    platform: linux/amd64
    command: >
      sh -c "./bin/init-chain && \
             ./bin/modify-app && \
             ./bin/modify-config && \
             exec ${BIN_NAME} start"
    environment:
      HOME: /home/${APP_NAME}
      DENOM: ${DENOM}
      NUM_VALIDATORS: ${NUM_VALIDATORS}
    volumes:
      - /home/${APP_NAME}
      - ./bin/:/home/${APP_NAME}/bin/
      - shared:/home/${APP_NAME}/.shared/
      - ./mnemonics.json:/home/${APP_NAME}/mnemonics.json
    networks:
      - default
    deploy:
      replicas: ${NUM_VALIDATORS}
