name: chihuahua-build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/builder'
      - 'arch.Dockerfile'
      - 'alpine.Dockerfile'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/chihuahua-build.yml'

  push:
    branches:
      - main
    paths:
      - 'bin/builder'
      - 'arch.Dockerfile'
      - 'alpine.Dockerfile'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/chihuahua-build.yml'

jobs:
  chihuahua-build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        #platform: ["linux/amd64", "linux/arm64"] # need arm runners
        platform: ["linux/amd64"]
        distro: ["alpine"]
        version:
          - "1.0.0"
          - "1.1.0"
          - "2.0.1"
          - "2.0.2"
          - "2.1.0"
          - "2.2.1"
          - "3.1.0"
          - "4.0.0"
          - "4.1.0"
          - "4.2.0"
          - "4.2.3"
          - "5.0.0"
          - "5.0.1"
          - "5.0.2"
          - "5.0.3"
          - "5.0.4"
          - "6"
        
        include:
          # Include Defaults (keep at top)
          - name: "chihuahua"
            binary: "chihuahuad"
            build_command: "make install"
            chain_registry_name: "chihuahua"
            go_version: "1.20.10"
            repo: "ChihuahuaChain/chihuahua"
            os: "linux"
            arch: "amd64"
        
          
          - version: "1.0.0"
            go_version: "1.16"
          - version: "1.1.0"
            go_version: "1.17"
          - version: "2.0.1"
            go_version: "1.17"
          - version: "2.0.2"
            go_version: "1.17"
          - version: "2.1.0"
            go_version: "1.18"
          - version: "2.2.1"
            go_version: "1.18"
          - version: "3.1.0"
            go_version: "1.19"
          - version: "4.0.0"
            go_version: "1.19"
          - version: "4.1.0"
            go_version: "1.19"
          - version: "4.2.0"
            go_version: "1.19"
          - version: "4.2.3"
            go_version: "1.19"

    with:
      binary: ${{ matrix.binary }}
      build_command: ${{ matrix.build_command }}
      chain_registry_name: ${{ matrix.chain_registry_name }}
      go_version: ${{ matrix.go_version }}
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      distro: ${{ matrix.distro }}
      platform: ${{ matrix.platform }}
      repo: ${{ matrix.repo }}
      version: ${{ matrix.version }}
