name: mars-build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/builder'
      - 'arch.Dockerfile'
      - 'alpine.Dockerfile'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/mars-build.yml'

  push:
    branches:
      - main
    paths:
      - 'bin/builder'
      - 'arch.Dockerfile'
      - 'alpine.Dockerfile'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/mars-build.yml'

jobs:
  terra-build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        #platform: ["linux/amd64", "linux/arm64"] # need arm runners
        platform: ["linux/amd64"]
        distro: ["alpine"]
        version:
          - "1.0.2"
        
        include:
          # Include Defaults (keep at top)
          - name: "mars"
            binary: "marsd"
            build_command: "make install"
            chain_registry_name: "mars"
            go_version: "1.20.8"
            repo: "mars-protocol/hub"
            os: "linux"
            arch: "amd64"
        
    with:
      binary: ${{ matrix.binary }}
      build_command: ${{ matrix.build_command }}
      chain_registry_name: ${{ matrix.chain_registry_name }}
      go_version: ${{ matrix.go_version }}
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      distro: ${{ matrix.distro }}
      platform: ${{ matrix.platform }}
      repo: ${{ matrix.repo }}
      version: ${{ matrix.version }}
