name: terra-build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'bin/builder'
      - 'arch.Dockerfile'
      - 'alpine.Dockerfile'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/terra-build.yml'

  push:
    branches:
      - main
    paths:
      - 'bin/builder'
      - 'arch.Dockerfile'
      - 'alpine.Dockerfile'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/terra-build.yml'

jobs:
  terra-build:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        #platform: ["linux/amd64", "linux/arm64"] # need arm runners
        platform: ["linux/amd64"]
        distro: ["alpine", "arch"]
        version:
          - "2.4.1"
          - "2.4.0"
          - "2.3.5"
        
        include:
          # Include Defaults (keep at top)
          - name: "terra"
            binary: "terrad"
            build_command: "make install"
            build_tags: "muslc"
            chain_registry_name: "terra2"
            cosmos_build_options: "nostrip"
            go_version: "1.20.8"
            mimalloc_version:
            repo: "terra-money/core"
            target: "prod"
            os: "linux"
            arch: "amd64"

          - distro: alpine
            ldflags: "-linkmode external -extldflags \"-Wl,-z,muldefs -static\""

          - distro: arch
            ldflags: ""

          # Includes per version
          - version: "2.3.5"
            go_version: "1.19.13"
        
    with:
      binary: ${{ matrix.binary }}
      build_command: ${{ matrix.build_command }}
      build_tags: ${{ matrix.build_tags }}
      chain_registry_name: ${{ matrix.chain_registry_name }}
      cosmos_build_options: ${{ matrix.cosmos_build_options }}
      go_version: ${{ matrix.go_version }}
      ldflags: ${{ matrix.ldflags }}
      mimalloc_version: ${{ matrix.mimalloc_version }}
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      distro: ${{ matrix.distro }}
      platform: ${{ matrix.platform }}
      repo: ${{ matrix.repo }}
      target: ${{ matrix.target }}
      version: ${{ matrix.version }}
